name: Makefile CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocstrings-python mkdocs-material mkdocs-jupyter
      
    - name: Deploy docs
      run: mkdocs gh-deploy --force
      
